/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client;

import com.bbn.takml_server.client.models.AddModelMetricsRequest;
import com.bbn.takml_server.client.models.ModelMetrics;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ModelMetricsApi
 */
@Ignore
public class ModelMetricsApiTest {

    private final ModelMetricsApi api = new ModelMetricsApi();

    /**
     * Add Model Inference Metrics
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addModelMetricsTest() throws Exception {
        AddModelMetricsRequest body = null;
        Object response = api.addModelMetrics(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteModelMetricsTest() throws Exception {
        String modelName = null;
        String modelVersion = null;
        Object response = api.deleteModelMetrics(modelName, modelVersion);

        // TODO: test validations
    }
    /**
     * Get All Model Metrics
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllModelMetricsTest() throws Exception {
        List<ModelMetrics> response = api.getAllModelMetrics();

        // TODO: test validations
    }
    /**
     * Get Model Metrics
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getModelMetricsTest() throws Exception {
        String modelName = null;
        String modelVersion = null;
        Object response = api.getModelMetrics(modelName, modelVersion);

        // TODO: test validations
    }
}
