/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client;

import com.bbn.takml_server.client.models.AddTakmlModelWrapperRequest;
import com.bbn.takml_server.client.models.EditTakmlModelWrapperRequest;
import com.bbn.takml_server.client.models.IndexRow;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ModelManagementApi
 */
@Ignore
public class ModelManagementApiTest {

    private final ModelManagementApi api = new ModelManagementApi();

    /**
     * Download a model binary by model hash
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void downloadModelTest() throws Exception {
        String modelHash = null;
        byte[] response = api.downloadModel(modelHash);

        // TODO: test validations
    }

    /**
     * Get metadata for all models
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getModelsTest() throws Exception {
        List<IndexRow> response = api.getModels();

        // TODO: test validations
    }
    /**
     * Remove a model by hash
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void removeModelTest() throws Exception {
        String hash = null;
        Object response = api.removeModel(hash);

        // TODO: test validations
    }
    /**
     * Search Models
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchModelsTest() throws Exception {
        String modelName = null;
        String modelType = null;
        List<IndexRow> response = api.searchModels(modelName, modelType);

        // TODO: test validations
    }
}
