/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client;

import com.bbn.takml_server.client.models.FeedbackResponse;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ModelFeedbackApi
 */
@Ignore
public class ModelFeedbackApiTest {

    private final ModelFeedbackApi api = new ModelFeedbackApi();

    /**
     * Add feedback to model
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addModelFeedbackTest() throws Exception {
        String modelName = null;
        Double modelVersion = null;
        String callsign = null;
        String inputText = null;
        File inputFile = null;
        String output = null;
        Boolean isCorrect = null;
        String outputErrorType = null;
        Integer evaluationConfidence = null;
        Integer evaluationRating = null;
        String comment = null;
        Boolean validInput = null;
        Object response = api.addModelFeedback(modelName, modelVersion, callsign, inputText, inputFile, output, isCorrect, outputErrorType, evaluationConfidence, evaluationRating, comment, validInput);

        // TODO: test validations
    }
    /**
     * Get all feedback for a model
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFeedbackForModelTest() throws Exception {
        String modelName = null;
        Double modelVersion = null;
        List<FeedbackResponse> response = api.getFeedbackForModel(modelName, modelVersion);

        // TODO: test validations
    }
}
