/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * AddFeedbackRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class AddFeedbackRequest {
  @SerializedName("modelName")
  private String modelName = null;

  @SerializedName("modelVersion")
  private Double modelVersion = null;

  @SerializedName("callsign")
  private String callsign = null;

  @SerializedName("inputText")
  private String inputText = null;

  @SerializedName("inputFile")
  private File inputFile = null;

  @SerializedName("output")
  private String output = null;

  @SerializedName("isCorrect")
  private Boolean isCorrect = null;

  /**
   * Gets or Sets outputErrorType
   */
  @JsonAdapter(OutputErrorTypeEnum.Adapter.class)
  public enum OutputErrorTypeEnum {
    @SerializedName("FALSE_POSITIVE")
    FALSE_POSITIVE("FALSE_POSITIVE"),
    @SerializedName("FALSE_NEGATIVE")
    FALSE_NEGATIVE("FALSE_NEGATIVE"),
    @SerializedName("INCORRECT_LABEL")
    INCORRECT_LABEL("INCORRECT_LABEL"),
    @SerializedName("MISSING_LABEL")
    MISSING_LABEL("MISSING_LABEL"),
    @SerializedName("OTHER")
    OTHER("OTHER");

    private String value;

    OutputErrorTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static OutputErrorTypeEnum fromValue(String input) {
      for (OutputErrorTypeEnum b : OutputErrorTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<OutputErrorTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OutputErrorTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public OutputErrorTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return OutputErrorTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("outputErrorType")
  private OutputErrorTypeEnum outputErrorType = null;

  @SerializedName("evaluationConfidence")
  private Integer evaluationConfidence = null;

  @SerializedName("evaluationRating")
  private Integer evaluationRating = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("validInput")
  private Boolean validInput = null;

  public AddFeedbackRequest modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * Get modelName
   * @return modelName
  **/
  @Schema(required = true, description = "")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public AddFeedbackRequest modelVersion(Double modelVersion) {
    this.modelVersion = modelVersion;
    return this;
  }

   /**
   * Get modelVersion
   * @return modelVersion
  **/
  @Schema(required = true, description = "")
  public Double getModelVersion() {
    return modelVersion;
  }

  public void setModelVersion(Double modelVersion) {
    this.modelVersion = modelVersion;
  }

  public AddFeedbackRequest callsign(String callsign) {
    this.callsign = callsign;
    return this;
  }

   /**
   * Get callsign
   * @return callsign
  **/
  @Schema(required = true, description = "")
  public String getCallsign() {
    return callsign;
  }

  public void setCallsign(String callsign) {
    this.callsign = callsign;
  }

  public AddFeedbackRequest inputText(String inputText) {
    this.inputText = inputText;
    return this;
  }

   /**
   * Get inputText
   * @return inputText
  **/
  @Schema(description = "")
  public String getInputText() {
    return inputText;
  }

  public void setInputText(String inputText) {
    this.inputText = inputText;
  }

  public AddFeedbackRequest inputFile(File inputFile) {
    this.inputFile = inputFile;
    return this;
  }

   /**
   * Get inputFile
   * @return inputFile
  **/
  @Schema(description = "")
  public File getInputFile() {
    return inputFile;
  }

  public void setInputFile(File inputFile) {
    this.inputFile = inputFile;
  }

  public AddFeedbackRequest output(String output) {
    this.output = output;
    return this;
  }

   /**
   * Get output
   * @return output
  **/
  @Schema(required = true, description = "")
  public String getOutput() {
    return output;
  }

  public void setOutput(String output) {
    this.output = output;
  }

  public AddFeedbackRequest isCorrect(Boolean isCorrect) {
    this.isCorrect = isCorrect;
    return this;
  }

   /**
   * Get isCorrect
   * @return isCorrect
  **/
  @Schema(required = true, description = "")
  public Boolean isIsCorrect() {
    return isCorrect;
  }

  public void setIsCorrect(Boolean isCorrect) {
    this.isCorrect = isCorrect;
  }

  public AddFeedbackRequest outputErrorType(OutputErrorTypeEnum outputErrorType) {
    this.outputErrorType = outputErrorType;
    return this;
  }

   /**
   * Get outputErrorType
   * @return outputErrorType
  **/
  @Schema(description = "")
  public OutputErrorTypeEnum getOutputErrorType() {
    return outputErrorType;
  }

  public void setOutputErrorType(OutputErrorTypeEnum outputErrorType) {
    this.outputErrorType = outputErrorType;
  }

  public AddFeedbackRequest evaluationConfidence(Integer evaluationConfidence) {
    this.evaluationConfidence = evaluationConfidence;
    return this;
  }

   /**
   * Get evaluationConfidence
   * minimum: 1
   * maximum: 5
   * @return evaluationConfidence
  **/
  @Schema(description = "")
  public Integer getEvaluationConfidence() {
    return evaluationConfidence;
  }

  public void setEvaluationConfidence(Integer evaluationConfidence) {
    this.evaluationConfidence = evaluationConfidence;
  }

  public AddFeedbackRequest evaluationRating(Integer evaluationRating) {
    this.evaluationRating = evaluationRating;
    return this;
  }

   /**
   * Get evaluationRating
   * minimum: 1
   * maximum: 5
   * @return evaluationRating
  **/
  @Schema(description = "")
  public Integer getEvaluationRating() {
    return evaluationRating;
  }

  public void setEvaluationRating(Integer evaluationRating) {
    this.evaluationRating = evaluationRating;
  }

  public AddFeedbackRequest comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @Schema(description = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public AddFeedbackRequest validInput(Boolean validInput) {
    this.validInput = validInput;
    return this;
  }

   /**
   * Get validInput
   * @return validInput
  **/
  @Schema(description = "")
  public Boolean isValidInput() {
    return validInput;
  }

  public void setValidInput(Boolean validInput) {
    this.validInput = validInput;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddFeedbackRequest addFeedbackRequest = (AddFeedbackRequest) o;
    return Objects.equals(this.modelName, addFeedbackRequest.modelName) &&
        Objects.equals(this.modelVersion, addFeedbackRequest.modelVersion) &&
        Objects.equals(this.callsign, addFeedbackRequest.callsign) &&
        Objects.equals(this.inputText, addFeedbackRequest.inputText) &&
        Objects.equals(this.inputFile, addFeedbackRequest.inputFile) &&
        Objects.equals(this.output, addFeedbackRequest.output) &&
        Objects.equals(this.isCorrect, addFeedbackRequest.isCorrect) &&
        Objects.equals(this.outputErrorType, addFeedbackRequest.outputErrorType) &&
        Objects.equals(this.evaluationConfidence, addFeedbackRequest.evaluationConfidence) &&
        Objects.equals(this.evaluationRating, addFeedbackRequest.evaluationRating) &&
        Objects.equals(this.comment, addFeedbackRequest.comment) &&
        Objects.equals(this.validInput, addFeedbackRequest.validInput);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modelName, modelVersion, callsign, inputText, Objects.hashCode(inputFile), output, isCorrect, outputErrorType, evaluationConfidence, evaluationRating, comment, validInput);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddFeedbackRequest {\n");
    
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    modelVersion: ").append(toIndentedString(modelVersion)).append("\n");
    sb.append("    callsign: ").append(toIndentedString(callsign)).append("\n");
    sb.append("    inputText: ").append(toIndentedString(inputText)).append("\n");
    sb.append("    inputFile: ").append(toIndentedString(inputFile)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    isCorrect: ").append(toIndentedString(isCorrect)).append("\n");
    sb.append("    outputErrorType: ").append(toIndentedString(outputErrorType)).append("\n");
    sb.append("    evaluationConfidence: ").append(toIndentedString(evaluationConfidence)).append("\n");
    sb.append("    evaluationRating: ").append(toIndentedString(evaluationRating)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    validInput: ").append(toIndentedString(validInput)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
