/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.bbn.takml_server.client.models.DeviceMetadata;
import com.bbn.takml_server.client.models.InferenceMetric;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AddModelMetricsRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class AddModelMetricsRequest {
  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("modelName")
  private String modelName = null;

  @SerializedName("modelVersion")
  private Double modelVersion = null;

  @SerializedName("deviceMetadata")
  private DeviceMetadata deviceMetadata = null;

  @SerializedName("inferenceMetrics")
  private List<InferenceMetric> inferenceMetrics = null;

  public AddModelMetricsRequest requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  @Schema(description = "")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public AddModelMetricsRequest modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * Get modelName
   * @return modelName
  **/
  @Schema(description = "")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public AddModelMetricsRequest modelVersion(Double modelVersion) {
    this.modelVersion = modelVersion;
    return this;
  }

   /**
   * Get modelVersion
   * @return modelVersion
  **/
  @Schema(description = "")
  public Double getModelVersion() {
    return modelVersion;
  }

  public void setModelVersion(Double modelVersion) {
    this.modelVersion = modelVersion;
  }

  public AddModelMetricsRequest deviceMetadata(DeviceMetadata deviceMetadata) {
    this.deviceMetadata = deviceMetadata;
    return this;
  }

   /**
   * Get deviceMetadata
   * @return deviceMetadata
  **/
  @Schema(description = "")
  public DeviceMetadata getDeviceMetadata() {
    return deviceMetadata;
  }

  public void setDeviceMetadata(DeviceMetadata deviceMetadata) {
    this.deviceMetadata = deviceMetadata;
  }

  public AddModelMetricsRequest inferenceMetrics(List<InferenceMetric> inferenceMetrics) {
    this.inferenceMetrics = inferenceMetrics;
    return this;
  }

  public AddModelMetricsRequest addInferenceMetricsItem(InferenceMetric inferenceMetricsItem) {
    if (this.inferenceMetrics == null) {
      this.inferenceMetrics = new ArrayList<InferenceMetric>();
    }
    this.inferenceMetrics.add(inferenceMetricsItem);
    return this;
  }

   /**
   * Get inferenceMetrics
   * @return inferenceMetrics
  **/
  @Schema(description = "")
  public List<InferenceMetric> getInferenceMetrics() {
    return inferenceMetrics;
  }

  public void setInferenceMetrics(List<InferenceMetric> inferenceMetrics) {
    this.inferenceMetrics = inferenceMetrics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddModelMetricsRequest addModelMetricsRequest = (AddModelMetricsRequest) o;
    return Objects.equals(this.requestId, addModelMetricsRequest.requestId) &&
        Objects.equals(this.modelName, addModelMetricsRequest.modelName) &&
        Objects.equals(this.modelVersion, addModelMetricsRequest.modelVersion) &&
        Objects.equals(this.deviceMetadata, addModelMetricsRequest.deviceMetadata) &&
        Objects.equals(this.inferenceMetrics, addModelMetricsRequest.inferenceMetrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, modelName, modelVersion, deviceMetadata, inferenceMetrics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddModelMetricsRequest {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    modelVersion: ").append(toIndentedString(modelVersion)).append("\n");
    sb.append("    deviceMetadata: ").append(toIndentedString(deviceMetadata)).append("\n");
    sb.append("    inferenceMetrics: ").append(toIndentedString(inferenceMetrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
