/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * AddTakmlModelWrapperRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class AddTakmlModelWrapperRequest {
  @SerializedName("takmlModelWrapper")
  private File takmlModelWrapper = null;

  @SerializedName("requesterCallsign")
  private String requesterCallsign = null;

  @SerializedName("runOnServer")
  private Boolean runOnServer = null;

  @SerializedName("supportedDevices")
  private List<String> supportedDevices = null;

  public AddTakmlModelWrapperRequest takmlModelWrapper(File takmlModelWrapper) {
    this.takmlModelWrapper = takmlModelWrapper;
    return this;
  }

   /**
   * Get takmlModelWrapper
   * @return takmlModelWrapper
  **/
  @Schema(description = "")
  public File getTakmlModelWrapper() {
    return takmlModelWrapper;
  }

  public void setTakmlModelWrapper(File takmlModelWrapper) {
    this.takmlModelWrapper = takmlModelWrapper;
  }

  public AddTakmlModelWrapperRequest requesterCallsign(String requesterCallsign) {
    this.requesterCallsign = requesterCallsign;
    return this;
  }

   /**
   * Get requesterCallsign
   * @return requesterCallsign
  **/
  @Schema(description = "")
  public String getRequesterCallsign() {
    return requesterCallsign;
  }

  public void setRequesterCallsign(String requesterCallsign) {
    this.requesterCallsign = requesterCallsign;
  }

  public AddTakmlModelWrapperRequest runOnServer(Boolean runOnServer) {
    this.runOnServer = runOnServer;
    return this;
  }

   /**
   * Get runOnServer
   * @return runOnServer
  **/
  @Schema(description = "")
  public Boolean isRunOnServer() {
    return runOnServer;
  }

  public void setRunOnServer(Boolean runOnServer) {
    this.runOnServer = runOnServer;
  }

  public AddTakmlModelWrapperRequest supportedDevices(List<String> supportedDevices) {
    this.supportedDevices = supportedDevices;
    return this;
  }

  public AddTakmlModelWrapperRequest addSupportedDevicesItem(String supportedDevicesItem) {
    if (this.supportedDevices == null) {
      this.supportedDevices = new ArrayList<String>();
    }
    this.supportedDevices.add(supportedDevicesItem);
    return this;
  }

   /**
   * Get supportedDevices
   * @return supportedDevices
  **/
  @Schema(description = "")
  public List<String> getSupportedDevices() {
    return supportedDevices;
  }

  public void setSupportedDevices(List<String> supportedDevices) {
    this.supportedDevices = supportedDevices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddTakmlModelWrapperRequest addTakmlModelWrapperRequest = (AddTakmlModelWrapperRequest) o;
    return Objects.equals(this.takmlModelWrapper, addTakmlModelWrapperRequest.takmlModelWrapper) &&
        Objects.equals(this.requesterCallsign, addTakmlModelWrapperRequest.requesterCallsign) &&
        Objects.equals(this.runOnServer, addTakmlModelWrapperRequest.runOnServer) &&
        Objects.equals(this.supportedDevices, addTakmlModelWrapperRequest.supportedDevices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(takmlModelWrapper), requesterCallsign, runOnServer, supportedDevices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddTakmlModelWrapperRequest {\n");
    
    sb.append("    takmlModelWrapper: ").append(toIndentedString(takmlModelWrapper)).append("\n");
    sb.append("    requesterCallsign: ").append(toIndentedString(requesterCallsign)).append("\n");
    sb.append("    runOnServer: ").append(toIndentedString(runOnServer)).append("\n");
    sb.append("    supportedDevices: ").append(toIndentedString(supportedDevices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
