/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * FeedbackResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class FeedbackResponse {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("modelName")
  private String modelName = null;

  @SerializedName("modelVersion")
  private Double modelVersion = null;

  @SerializedName("callsign")
  private String callsign = null;

  /**
   * Gets or Sets inputType
   */
  @JsonAdapter(InputTypeEnum.Adapter.class)
  public enum InputTypeEnum {
    @SerializedName("TEXT")
    TEXT("TEXT"),
    @SerializedName("IMAGE")
    IMAGE("IMAGE"),
    @SerializedName("AUDIO")
    AUDIO("AUDIO"),
    @SerializedName("OTHER")
    OTHER("OTHER");

    private String value;

    InputTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static InputTypeEnum fromValue(String input) {
      for (InputTypeEnum b : InputTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<InputTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final InputTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public InputTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return InputTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("inputType")
  private InputTypeEnum inputType = null;

  @SerializedName("input")
  private String input = null;

  @SerializedName("output")
  private String output = null;

  @SerializedName("isCorrect")
  private Boolean isCorrect = null;

  /**
   * Gets or Sets outputErrorType
   */
  @JsonAdapter(OutputErrorTypeEnum.Adapter.class)
  public enum OutputErrorTypeEnum {
    @SerializedName("FALSE_POSITIVE")
    FALSE_POSITIVE("FALSE_POSITIVE"),
    @SerializedName("FALSE_NEGATIVE")
    FALSE_NEGATIVE("FALSE_NEGATIVE"),
    @SerializedName("INCORRECT_LABEL")
    INCORRECT_LABEL("INCORRECT_LABEL"),
    @SerializedName("MISSING_LABEL")
    MISSING_LABEL("MISSING_LABEL"),
    @SerializedName("OTHER")
    OTHER("OTHER");

    private String value;

    OutputErrorTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static OutputErrorTypeEnum fromValue(String input) {
      for (OutputErrorTypeEnum b : OutputErrorTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<OutputErrorTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OutputErrorTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public OutputErrorTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return OutputErrorTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("outputErrorType")
  private OutputErrorTypeEnum outputErrorType = null;

  @SerializedName("evaluationConfidence")
  private Integer evaluationConfidence = null;

  @SerializedName("evaluationRating")
  private Integer evaluationRating = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  public FeedbackResponse id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public FeedbackResponse modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * Get modelName
   * @return modelName
  **/
  @Schema(description = "")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public FeedbackResponse modelVersion(Double modelVersion) {
    this.modelVersion = modelVersion;
    return this;
  }

   /**
   * Get modelVersion
   * @return modelVersion
  **/
  @Schema(description = "")
  public Double getModelVersion() {
    return modelVersion;
  }

  public void setModelVersion(Double modelVersion) {
    this.modelVersion = modelVersion;
  }

  public FeedbackResponse callsign(String callsign) {
    this.callsign = callsign;
    return this;
  }

   /**
   * Get callsign
   * @return callsign
  **/
  @Schema(description = "")
  public String getCallsign() {
    return callsign;
  }

  public void setCallsign(String callsign) {
    this.callsign = callsign;
  }

  public FeedbackResponse inputType(InputTypeEnum inputType) {
    this.inputType = inputType;
    return this;
  }

   /**
   * Get inputType
   * @return inputType
  **/
  @Schema(description = "")
  public InputTypeEnum getInputType() {
    return inputType;
  }

  public void setInputType(InputTypeEnum inputType) {
    this.inputType = inputType;
  }

  public FeedbackResponse input(String input) {
    this.input = input;
    return this;
  }

   /**
   * Get input
   * @return input
  **/
  @Schema(description = "")
  public String getInput() {
    return input;
  }

  public void setInput(String input) {
    this.input = input;
  }

  public FeedbackResponse output(String output) {
    this.output = output;
    return this;
  }

   /**
   * Get output
   * @return output
  **/
  @Schema(description = "")
  public String getOutput() {
    return output;
  }

  public void setOutput(String output) {
    this.output = output;
  }

  public FeedbackResponse isCorrect(Boolean isCorrect) {
    this.isCorrect = isCorrect;
    return this;
  }

   /**
   * Get isCorrect
   * @return isCorrect
  **/
  @Schema(description = "")
  public Boolean isIsCorrect() {
    return isCorrect;
  }

  public void setIsCorrect(Boolean isCorrect) {
    this.isCorrect = isCorrect;
  }

  public FeedbackResponse outputErrorType(OutputErrorTypeEnum outputErrorType) {
    this.outputErrorType = outputErrorType;
    return this;
  }

   /**
   * Get outputErrorType
   * @return outputErrorType
  **/
  @Schema(description = "")
  public OutputErrorTypeEnum getOutputErrorType() {
    return outputErrorType;
  }

  public void setOutputErrorType(OutputErrorTypeEnum outputErrorType) {
    this.outputErrorType = outputErrorType;
  }

  public FeedbackResponse evaluationConfidence(Integer evaluationConfidence) {
    this.evaluationConfidence = evaluationConfidence;
    return this;
  }

   /**
   * Get evaluationConfidence
   * @return evaluationConfidence
  **/
  @Schema(description = "")
  public Integer getEvaluationConfidence() {
    return evaluationConfidence;
  }

  public void setEvaluationConfidence(Integer evaluationConfidence) {
    this.evaluationConfidence = evaluationConfidence;
  }

  public FeedbackResponse evaluationRating(Integer evaluationRating) {
    this.evaluationRating = evaluationRating;
    return this;
  }

   /**
   * Get evaluationRating
   * @return evaluationRating
  **/
  @Schema(description = "")
  public Integer getEvaluationRating() {
    return evaluationRating;
  }

  public void setEvaluationRating(Integer evaluationRating) {
    this.evaluationRating = evaluationRating;
  }

  public FeedbackResponse comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @Schema(description = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public FeedbackResponse createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeedbackResponse feedbackResponse = (FeedbackResponse) o;
    return Objects.equals(this.id, feedbackResponse.id) &&
        Objects.equals(this.modelName, feedbackResponse.modelName) &&
        Objects.equals(this.modelVersion, feedbackResponse.modelVersion) &&
        Objects.equals(this.callsign, feedbackResponse.callsign) &&
        Objects.equals(this.inputType, feedbackResponse.inputType) &&
        Objects.equals(this.input, feedbackResponse.input) &&
        Objects.equals(this.output, feedbackResponse.output) &&
        Objects.equals(this.isCorrect, feedbackResponse.isCorrect) &&
        Objects.equals(this.outputErrorType, feedbackResponse.outputErrorType) &&
        Objects.equals(this.evaluationConfidence, feedbackResponse.evaluationConfidence) &&
        Objects.equals(this.evaluationRating, feedbackResponse.evaluationRating) &&
        Objects.equals(this.comment, feedbackResponse.comment) &&
        Objects.equals(this.createdAt, feedbackResponse.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, modelName, modelVersion, callsign, inputType, input, output, isCorrect, outputErrorType, evaluationConfidence, evaluationRating, comment, createdAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeedbackResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    modelVersion: ").append(toIndentedString(modelVersion)).append("\n");
    sb.append("    callsign: ").append(toIndentedString(callsign)).append("\n");
    sb.append("    inputType: ").append(toIndentedString(inputType)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    isCorrect: ").append(toIndentedString(isCorrect)).append("\n");
    sb.append("    outputErrorType: ").append(toIndentedString(outputErrorType)).append("\n");
    sb.append("    evaluationConfidence: ").append(toIndentedString(evaluationConfidence)).append("\n");
    sb.append("    evaluationRating: ").append(toIndentedString(evaluationRating)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
