/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * IndexRow
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class IndexRow {
  @SerializedName("hash")
  private String hash = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("additionalMetadata")
  private Map<String, String> additionalMetadata = null;

  @SerializedName("timeMillisToCallsign")
  private Map<String, String> timeMillisToCallsign = null;

  @SerializedName("optionalSegments")
  private Map<String, String> optionalSegments = null;

  public IndexRow hash(String hash) {
    this.hash = hash;
    return this;
  }

   /**
   * Get hash
   * @return hash
  **/
  @Schema(description = "")
  public String getHash() {
    return hash;
  }

  public void setHash(String hash) {
    this.hash = hash;
  }

  public IndexRow name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IndexRow additionalMetadata(Map<String, String> additionalMetadata) {
    this.additionalMetadata = additionalMetadata;
    return this;
  }

  public IndexRow putAdditionalMetadataItem(String key, String additionalMetadataItem) {
    if (this.additionalMetadata == null) {
      this.additionalMetadata = new HashMap<String, String>();
    }
    this.additionalMetadata.put(key, additionalMetadataItem);
    return this;
  }

   /**
   * Get additionalMetadata
   * @return additionalMetadata
  **/
  @Schema(description = "")
  public Map<String, String> getAdditionalMetadata() {
    return additionalMetadata;
  }

  public void setAdditionalMetadata(Map<String, String> additionalMetadata) {
    this.additionalMetadata = additionalMetadata;
  }

  public IndexRow timeMillisToCallsign(Map<String, String> timeMillisToCallsign) {
    this.timeMillisToCallsign = timeMillisToCallsign;
    return this;
  }

  public IndexRow putTimeMillisToCallsignItem(String key, String timeMillisToCallsignItem) {
    if (this.timeMillisToCallsign == null) {
      this.timeMillisToCallsign = new HashMap<String, String>();
    }
    this.timeMillisToCallsign.put(key, timeMillisToCallsignItem);
    return this;
  }

   /**
   * Get timeMillisToCallsign
   * @return timeMillisToCallsign
  **/
  @Schema(description = "")
  public Map<String, String> getTimeMillisToCallsign() {
    return timeMillisToCallsign;
  }

  public void setTimeMillisToCallsign(Map<String, String> timeMillisToCallsign) {
    this.timeMillisToCallsign = timeMillisToCallsign;
  }

  public IndexRow optionalSegments(Map<String, String> optionalSegments) {
    this.optionalSegments = optionalSegments;
    return this;
  }

  public IndexRow putOptionalSegmentsItem(String key, String optionalSegmentsItem) {
    if (this.optionalSegments == null) {
      this.optionalSegments = new HashMap<String, String>();
    }
    this.optionalSegments.put(key, optionalSegmentsItem);
    return this;
  }

   /**
   * Get optionalSegments
   * @return optionalSegments
  **/
  @Schema(description = "")
  public Map<String, String> getOptionalSegments() {
    return optionalSegments;
  }

  public void setOptionalSegments(Map<String, String> optionalSegments) {
    this.optionalSegments = optionalSegments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndexRow indexRow = (IndexRow) o;
    return Objects.equals(this.hash, indexRow.hash) &&
        Objects.equals(this.name, indexRow.name) &&
        Objects.equals(this.additionalMetadata, indexRow.additionalMetadata) &&
        Objects.equals(this.timeMillisToCallsign, indexRow.timeMillisToCallsign) &&
        Objects.equals(this.optionalSegments, indexRow.optionalSegments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hash, name, additionalMetadata, timeMillisToCallsign, optionalSegments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndexRow {\n");
    
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    additionalMetadata: ").append(toIndentedString(additionalMetadata)).append("\n");
    sb.append("    timeMillisToCallsign: ").append(toIndentedString(timeMillisToCallsign)).append("\n");
    sb.append("    optionalSegments: ").append(toIndentedString(optionalSegments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
