/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InferenceMetric
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class InferenceMetric {
  @SerializedName("startMillis")
  private Long startMillis = null;

  @SerializedName("durationMillis")
  private Long durationMillis = null;

  @SerializedName("confidence")
  private Float confidence = null;

  public InferenceMetric startMillis(Long startMillis) {
    this.startMillis = startMillis;
    return this;
  }

   /**
   * Get startMillis
   * @return startMillis
  **/
  @Schema(description = "")
  public Long getStartMillis() {
    return startMillis;
  }

  public void setStartMillis(Long startMillis) {
    this.startMillis = startMillis;
  }

  public InferenceMetric durationMillis(Long durationMillis) {
    this.durationMillis = durationMillis;
    return this;
  }

   /**
   * Get durationMillis
   * @return durationMillis
  **/
  @Schema(description = "")
  public Long getDurationMillis() {
    return durationMillis;
  }

  public void setDurationMillis(Long durationMillis) {
    this.durationMillis = durationMillis;
  }

  public InferenceMetric confidence(Float confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Get confidence
   * @return confidence
  **/
  @Schema(description = "")
  public Float getConfidence() {
    return confidence;
  }

  public void setConfidence(Float confidence) {
    this.confidence = confidence;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InferenceMetric inferenceMetric = (InferenceMetric) o;
    return Objects.equals(this.startMillis, inferenceMetric.startMillis) &&
        Objects.equals(this.durationMillis, inferenceMetric.durationMillis) &&
        Objects.equals(this.confidence, inferenceMetric.confidence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startMillis, durationMillis, confidence);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InferenceMetric {\n");
    
    sb.append("    startMillis: ").append(toIndentedString(startMillis)).append("\n");
    sb.append("    durationMillis: ").append(toIndentedString(durationMillis)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
