/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.bbn.takml_server.client.models.InferInput;
import com.bbn.takml_server.client.models.Links;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Inference request payload
 */
@Schema(description = "Inference request payload")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class InferenceRequest {
  @SerializedName("_links")
  private Links _links = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("inputs")
  private List<InferInput> inputs = new ArrayList<InferInput>();

  public InferenceRequest _links(Links _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public Links getLinks() {
    return _links;
  }

  public void setLinks(Links _links) {
    this._links = _links;
  }

  public InferenceRequest id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the request
   * @return id
  **/
  @Schema(description = "Unique identifier for the request")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InferenceRequest inputs(List<InferInput> inputs) {
    this.inputs = inputs;
    return this;
  }

  public InferenceRequest addInputsItem(InferInput inputsItem) {
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Input data for inference
   * @return inputs
  **/
  @Schema(required = true, description = "Input data for inference")
  public List<InferInput> getInputs() {
    return inputs;
  }

  public void setInputs(List<InferInput> inputs) {
    this.inputs = inputs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InferenceRequest inferenceRequest = (InferenceRequest) o;
    return Objects.equals(this._links, inferenceRequest._links) &&
        Objects.equals(this.id, inferenceRequest.id) &&
        Objects.equals(this.inputs, inferenceRequest.inputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_links, id, inputs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InferenceRequest {\n");
    
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
