/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.bbn.takml_server.client.models.InferOutput;
import com.bbn.takml_server.client.models.Links;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InferenceResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class InferenceResponse {
  @SerializedName("_links")
  private Links _links = null;

  @SerializedName("model_name")
  private String modelName = null;

  @SerializedName("model_version")
  private String modelVersion = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("outputs")
  private List<InferOutput> outputs = new ArrayList<InferOutput>();

  public InferenceResponse _links(Links _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public Links getLinks() {
    return _links;
  }

  public void setLinks(Links _links) {
    this._links = _links;
  }

  public InferenceResponse modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * Name of the model
   * @return modelName
  **/
  @Schema(required = true, description = "Name of the model")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public InferenceResponse modelVersion(String modelVersion) {
    this.modelVersion = modelVersion;
    return this;
  }

   /**
   * Version of the model
   * @return modelVersion
  **/
  @Schema(description = "Version of the model")
  public String getModelVersion() {
    return modelVersion;
  }

  public void setModelVersion(String modelVersion) {
    this.modelVersion = modelVersion;
  }

  public InferenceResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the response
   * @return id
  **/
  @Schema(description = "Unique identifier for the response")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InferenceResponse outputs(List<InferOutput> outputs) {
    this.outputs = outputs;
    return this;
  }

  public InferenceResponse addOutputsItem(InferOutput outputsItem) {
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Output data from inference
   * @return outputs
  **/
  @Schema(required = true, description = "Output data from inference")
  public List<InferOutput> getOutputs() {
    return outputs;
  }

  public void setOutputs(List<InferOutput> outputs) {
    this.outputs = outputs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InferenceResponse inferenceResponse = (InferenceResponse) o;
    return Objects.equals(this._links, inferenceResponse._links) &&
        Objects.equals(this.modelName, inferenceResponse.modelName) &&
        Objects.equals(this.modelVersion, inferenceResponse.modelVersion) &&
        Objects.equals(this.id, inferenceResponse.id) &&
        Objects.equals(this.outputs, inferenceResponse.outputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_links, modelName, modelVersion, id, outputs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InferenceResponse {\n");
    
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    modelVersion: ").append(toIndentedString(modelVersion)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
