/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.bbn.takml_server.client.models.Links;
import com.bbn.takml_server.client.models.ModelTensor;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ModelMetadataResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class ModelMetadataResponse {
  @SerializedName("_links")
  private Links _links = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("versions")
  private List<String> versions = null;

  @SerializedName("platform")
  private String platform = null;

  @SerializedName("inputs")
  private List<ModelTensor> inputs = new ArrayList<ModelTensor>();

  @SerializedName("outputs")
  private List<ModelTensor> outputs = new ArrayList<ModelTensor>();

  public ModelMetadataResponse _links(Links _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public Links getLinks() {
    return _links;
  }

  public void setLinks(Links _links) {
    this._links = _links;
  }

  public ModelMetadataResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the model
   * @return name
  **/
  @Schema(required = true, description = "Name of the model")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ModelMetadataResponse versions(List<String> versions) {
    this.versions = versions;
    return this;
  }

  public ModelMetadataResponse addVersionsItem(String versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<String>();
    }
    this.versions.add(versionsItem);
    return this;
  }

   /**
   * Available versions of the model
   * @return versions
  **/
  @Schema(description = "Available versions of the model")
  public List<String> getVersions() {
    return versions;
  }

  public void setVersions(List<String> versions) {
    this.versions = versions;
  }

  public ModelMetadataResponse platform(String platform) {
    this.platform = platform;
    return this;
  }

   /**
   * Platform/framework of the model (e.g., \&quot;TensorFlow\&quot;, \&quot;PyTorch\&quot;)
   * @return platform
  **/
  @Schema(required = true, description = "Platform/framework of the model (e.g., \"TensorFlow\", \"PyTorch\")")
  public String getPlatform() {
    return platform;
  }

  public void setPlatform(String platform) {
    this.platform = platform;
  }

  public ModelMetadataResponse inputs(List<ModelTensor> inputs) {
    this.inputs = inputs;
    return this;
  }

  public ModelMetadataResponse addInputsItem(ModelTensor inputsItem) {
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Input tensors for the model
   * @return inputs
  **/
  @Schema(required = true, description = "Input tensors for the model")
  public List<ModelTensor> getInputs() {
    return inputs;
  }

  public void setInputs(List<ModelTensor> inputs) {
    this.inputs = inputs;
  }

  public ModelMetadataResponse outputs(List<ModelTensor> outputs) {
    this.outputs = outputs;
    return this;
  }

  public ModelMetadataResponse addOutputsItem(ModelTensor outputsItem) {
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Output tensors for the model
   * @return outputs
  **/
  @Schema(required = true, description = "Output tensors for the model")
  public List<ModelTensor> getOutputs() {
    return outputs;
  }

  public void setOutputs(List<ModelTensor> outputs) {
    this.outputs = outputs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelMetadataResponse modelMetadataResponse = (ModelMetadataResponse) o;
    return Objects.equals(this._links, modelMetadataResponse._links) &&
        Objects.equals(this.name, modelMetadataResponse.name) &&
        Objects.equals(this.versions, modelMetadataResponse.versions) &&
        Objects.equals(this.platform, modelMetadataResponse.platform) &&
        Objects.equals(this.inputs, modelMetadataResponse.inputs) &&
        Objects.equals(this.outputs, modelMetadataResponse.outputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_links, name, versions, platform, inputs, outputs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelMetadataResponse {\n");
    
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
