/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.bbn.takml_server.client.models.InferenceMetric;
import com.bbn.takml_server.client.models.ModelMetricsId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ModelMetrics
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class ModelMetrics {
  @SerializedName("id")
  private ModelMetricsId id = null;

  @SerializedName("inferenceMetricList")
  private List<InferenceMetric> inferenceMetricList = null;

  @SerializedName("modelName")
  private String modelName = null;

  @SerializedName("modelVersion")
  private Double modelVersion = null;

  public ModelMetrics id(ModelMetricsId id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public ModelMetricsId getId() {
    return id;
  }

  public void setId(ModelMetricsId id) {
    this.id = id;
  }

  public ModelMetrics inferenceMetricList(List<InferenceMetric> inferenceMetricList) {
    this.inferenceMetricList = inferenceMetricList;
    return this;
  }

  public ModelMetrics addInferenceMetricListItem(InferenceMetric inferenceMetricListItem) {
    if (this.inferenceMetricList == null) {
      this.inferenceMetricList = new ArrayList<InferenceMetric>();
    }
    this.inferenceMetricList.add(inferenceMetricListItem);
    return this;
  }

   /**
   * Get inferenceMetricList
   * @return inferenceMetricList
  **/
  @Schema(description = "")
  public List<InferenceMetric> getInferenceMetricList() {
    return inferenceMetricList;
  }

  public void setInferenceMetricList(List<InferenceMetric> inferenceMetricList) {
    this.inferenceMetricList = inferenceMetricList;
  }

  public ModelMetrics modelName(String modelName) {
    this.modelName = modelName;
    return this;
  }

   /**
   * Get modelName
   * @return modelName
  **/
  @Schema(description = "")
  public String getModelName() {
    return modelName;
  }

  public void setModelName(String modelName) {
    this.modelName = modelName;
  }

  public ModelMetrics modelVersion(Double modelVersion) {
    this.modelVersion = modelVersion;
    return this;
  }

   /**
   * Get modelVersion
   * @return modelVersion
  **/
  @Schema(description = "")
  public Double getModelVersion() {
    return modelVersion;
  }

  public void setModelVersion(Double modelVersion) {
    this.modelVersion = modelVersion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelMetrics modelMetrics = (ModelMetrics) o;
    return Objects.equals(this.id, modelMetrics.id) &&
        Objects.equals(this.inferenceMetricList, modelMetrics.inferenceMetricList) &&
        Objects.equals(this.modelName, modelMetrics.modelName) &&
        Objects.equals(this.modelVersion, modelMetrics.modelVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, inferenceMetricList, modelName, modelVersion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelMetrics {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inferenceMetricList: ").append(toIndentedString(inferenceMetricList)).append("\n");
    sb.append("    modelName: ").append(toIndentedString(modelName)).append("\n");
    sb.append("    modelVersion: ").append(toIndentedString(modelVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
