/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.bbn.takml_server.client.models.Links;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Output tensors for the model
 */
@Schema(description = "Output tensors for the model")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class ModelTensor {
  @SerializedName("_links")
  private Links _links = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("datatype")
  private String datatype = null;

  @SerializedName("shape")
  private List<Integer> shape = new ArrayList<Integer>();

  public ModelTensor _links(Links _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public Links getLinks() {
    return _links;
  }

  public void setLinks(Links _links) {
    this._links = _links;
  }

  public ModelTensor name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the tensor
   * @return name
  **/
  @Schema(required = true, description = "Name of the tensor")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ModelTensor datatype(String datatype) {
    this.datatype = datatype;
    return this;
  }

   /**
   * Data type of the tensor (e.g., \&quot;FP32\&quot;, \&quot;INT64\&quot;)
   * @return datatype
  **/
  @Schema(required = true, description = "Data type of the tensor (e.g., \"FP32\", \"INT64\")")
  public String getDatatype() {
    return datatype;
  }

  public void setDatatype(String datatype) {
    this.datatype = datatype;
  }

  public ModelTensor shape(List<Integer> shape) {
    this.shape = shape;
    return this;
  }

  public ModelTensor addShapeItem(Integer shapeItem) {
    this.shape.add(shapeItem);
    return this;
  }

   /**
   * Shape of the tensor
   * @return shape
  **/
  @Schema(required = true, description = "Shape of the tensor")
  public List<Integer> getShape() {
    return shape;
  }

  public void setShape(List<Integer> shape) {
    this.shape = shape;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelTensor modelTensor = (ModelTensor) o;
    return Objects.equals(this._links, modelTensor._links) &&
        Objects.equals(this.name, modelTensor.name) &&
        Objects.equals(this.datatype, modelTensor.datatype) &&
        Objects.equals(this.shape, modelTensor.shape);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_links, name, datatype, shape);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelTensor {\n");
    
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    datatype: ").append(toIndentedString(datatype)).append("\n");
    sb.append("    shape: ").append(toIndentedString(shape)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
