/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.bbn.takml_server.client.models.Links;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ServerMetadataResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-11-26T15:05:21.699098228-05:00[America/New_York]")

public class ServerMetadataResponse {
  @SerializedName("_links")
  private Links _links = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("extensions")
  private List<String> extensions = new ArrayList<String>();

  public ServerMetadataResponse _links(Links _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public Links getLinks() {
    return _links;
  }

  public void setLinks(Links _links) {
    this._links = _links;
  }

  public ServerMetadataResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the server
   * @return name
  **/
  @Schema(required = true, description = "Name of the server")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ServerMetadataResponse version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Version of the server
   * @return version
  **/
  @Schema(required = true, description = "Version of the server")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public ServerMetadataResponse extensions(List<String> extensions) {
    this.extensions = extensions;
    return this;
  }

  public ServerMetadataResponse addExtensionsItem(String extensionsItem) {
    this.extensions.add(extensionsItem);
    return this;
  }

   /**
   * Supported extensions
   * @return extensions
  **/
  @Schema(required = true, description = "Supported extensions")
  public List<String> getExtensions() {
    return extensions;
  }

  public void setExtensions(List<String> extensions) {
    this.extensions = extensions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerMetadataResponse serverMetadataResponse = (ServerMetadataResponse) o;
    return Objects.equals(this._links, serverMetadataResponse._links) &&
        Objects.equals(this.name, serverMetadataResponse.name) &&
        Objects.equals(this.version, serverMetadataResponse.version) &&
        Objects.equals(this.extensions, serverMetadataResponse.extensions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_links, name, version, extensions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerMetadataResponse {\n");
    
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
