/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bbn.takml_server.client;

import com.bbn.takml_server.ApiCallback;
import com.bbn.takml_server.ApiClient;
import com.bbn.takml_server.ApiException;
import com.bbn.takml_server.ApiResponse;
import com.bbn.takml_server.Configuration;
import com.bbn.takml_server.Pair;
import com.bbn.takml_server.ProgressRequestBody;
import com.bbn.takml_server.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.bbn.takml_server.client.models.ErrorResponse;
import com.bbn.takml_server.client.models.InferenceRequest;
import com.bbn.takml_server.client.models.InferenceResponse;
import com.bbn.takml_server.client.models.ModelMetadataResponse;
import com.bbn.takml_server.client.models.ServerMetadataResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ModelExecutionApi {
    private ApiClient apiClient;

    public ModelExecutionApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ModelExecutionApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getModelVersionMetadata
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public okhttp3.Call getModelVersionMetadataCall(String MODEL_NAME, String MODEL_VERSION, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/models/{MODEL_NAME}/versions/{MODEL_VERSION}"
            .replaceAll("\\{" + "MODEL_NAME" + "\\}", apiClient.escapeString(MODEL_NAME.toString()))
            .replaceAll("\\{" + "MODEL_VERSION" + "\\}", apiClient.escapeString(MODEL_VERSION.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new okhttp3.Interceptor() {
                @Override
                public okhttp3.Response intercept(okhttp3.Interceptor.Chain chain) throws IOException {
                    okhttp3.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getModelVersionMetadataValidateBeforeCall(String MODEL_NAME, String MODEL_VERSION, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'MODEL_NAME' is set
        if (MODEL_NAME == null) {
            throw new ApiException("Missing the required parameter 'MODEL_NAME' when calling getModelVersionMetadata(Async)");
        }
        // verify the required parameter 'MODEL_VERSION' is set
        if (MODEL_VERSION == null) {
            throw new ApiException("Missing the required parameter 'MODEL_VERSION' when calling getModelVersionMetadata(Async)");
        }

        okhttp3.Call call = getModelVersionMetadataCall(MODEL_NAME, MODEL_VERSION, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Model Version Metadata
     * Retrieves metadata for a specific version of a model. 
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @return ModelMetadataResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ModelMetadataResponse getModelVersionMetadata(String MODEL_NAME, String MODEL_VERSION) throws ApiException {
        ApiResponse<ModelMetadataResponse> resp = getModelVersionMetadataWithHttpInfo(MODEL_NAME, MODEL_VERSION);
        return resp.getData();
    }

    /**
     * Model Version Metadata
     * Retrieves metadata for a specific version of a model. 
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @return ApiResponse&lt;ModelMetadataResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ModelMetadataResponse> getModelVersionMetadataWithHttpInfo(String MODEL_NAME, String MODEL_VERSION) throws ApiException {
        okhttp3.Call call = getModelVersionMetadataValidateBeforeCall(MODEL_NAME, MODEL_VERSION, null, null);
        Type localVarReturnType = new TypeToken<ModelMetadataResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Model Version Metadata (asynchronously)
     * Retrieves metadata for a specific version of a model. 
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public okhttp3.Call getModelVersionMetadataAsync(String MODEL_NAME, String MODEL_VERSION, final ApiCallback<ModelMetadataResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        okhttp3.Call call = getModelVersionMetadataValidateBeforeCall(MODEL_NAME, MODEL_VERSION, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ModelMetadataResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getModelVersionReady
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public okhttp3.Call getModelVersionReadyCall(String MODEL_NAME, String MODEL_VERSION, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/models/{MODEL_NAME}/versions/{MODEL_VERSION}/ready"
            .replaceAll("\\{" + "MODEL_NAME" + "\\}", apiClient.escapeString(MODEL_NAME.toString()))
            .replaceAll("\\{" + "MODEL_VERSION" + "\\}", apiClient.escapeString(MODEL_VERSION.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new okhttp3.Interceptor() {
                @Override
                public okhttp3.Response intercept(okhttp3.Interceptor.Chain chain) throws IOException {
                    okhttp3.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getModelVersionReadyValidateBeforeCall(String MODEL_NAME, String MODEL_VERSION, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'MODEL_NAME' is set
        if (MODEL_NAME == null) {
            throw new ApiException("Missing the required parameter 'MODEL_NAME' when calling getModelVersionReady(Async)");
        }
        // verify the required parameter 'MODEL_VERSION' is set
        if (MODEL_VERSION == null) {
            throw new ApiException("Missing the required parameter 'MODEL_VERSION' when calling getModelVersionReady(Async)");
        }

        okhttp3.Call call = getModelVersionReadyCall(MODEL_NAME, MODEL_VERSION, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Model Version Ready
     * The \&quot;model version ready\&quot; API indicates if a specific version of a model is ready for inference. 
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void getModelVersionReady(String MODEL_NAME, String MODEL_VERSION) throws ApiException {
        getModelVersionReadyWithHttpInfo(MODEL_NAME, MODEL_VERSION);
    }

    /**
     * Model Version Ready
     * The \&quot;model version ready\&quot; API indicates if a specific version of a model is ready for inference. 
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> getModelVersionReadyWithHttpInfo(String MODEL_NAME, String MODEL_VERSION) throws ApiException {
        okhttp3.Call call = getModelVersionReadyValidateBeforeCall(MODEL_NAME, MODEL_VERSION, null, null);
        return apiClient.execute(call);
    }

    /**
     * Model Version Ready (asynchronously)
     * The \&quot;model version ready\&quot; API indicates if a specific version of a model is ready for inference. 
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public okhttp3.Call getModelVersionReadyAsync(String MODEL_NAME, String MODEL_VERSION, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        okhttp3.Call call = getModelVersionReadyValidateBeforeCall(MODEL_NAME, MODEL_VERSION, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for getServerMetadata
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public okhttp3.Call getServerMetadataCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new okhttp3.Interceptor() {
                @Override
                public okhttp3.Response intercept(okhttp3.Interceptor.Chain chain) throws IOException {
                    okhttp3.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getServerMetadataValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        okhttp3.Call call = getServerMetadataCall(progressListener, progressRequestListener);
        return call;

    }

    /**
     * Server Metadata
     * Retrieves metadata about the inference server. 
     * @return ServerMetadataResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ServerMetadataResponse getServerMetadata() throws ApiException {
        ApiResponse<ServerMetadataResponse> resp = getServerMetadataWithHttpInfo();
        return resp.getData();
    }

    /**
     * Server Metadata
     * Retrieves metadata about the inference server. 
     * @return ApiResponse&lt;ServerMetadataResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ServerMetadataResponse> getServerMetadataWithHttpInfo() throws ApiException {
        okhttp3.Call call = getServerMetadataValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<ServerMetadataResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Server Metadata (asynchronously)
     * Retrieves metadata about the inference server. 
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public okhttp3.Call getServerMetadataAsync(final ApiCallback<ServerMetadataResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        okhttp3.Call call = getServerMetadataValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ServerMetadataResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getV2HealthLive
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public okhttp3.Call getV2HealthLiveCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/health/live";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new okhttp3.Interceptor() {
                @Override
                public okhttp3.Response intercept(okhttp3.Interceptor.Chain chain) throws IOException {
                    okhttp3.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getV2HealthLiveValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        okhttp3.Call call = getV2HealthLiveCall(progressListener, progressRequestListener);
        return call;

    }

    /**
     * Server Live
     * The \&quot;server live\&quot; API indicates if the inference server is running and able to handle requests. This can be used for Kubernetes liveness probes. 
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void getV2HealthLive() throws ApiException {
        getV2HealthLiveWithHttpInfo();
    }

    /**
     * Server Live
     * The \&quot;server live\&quot; API indicates if the inference server is running and able to handle requests. This can be used for Kubernetes liveness probes. 
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> getV2HealthLiveWithHttpInfo() throws ApiException {
        okhttp3.Call call = getV2HealthLiveValidateBeforeCall(null, null);
        return apiClient.execute(call);
    }

    /**
     * Server Live (asynchronously)
     * The \&quot;server live\&quot; API indicates if the inference server is running and able to handle requests. This can be used for Kubernetes liveness probes. 
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public okhttp3.Call getV2HealthLiveAsync(final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        okhttp3.Call call = getV2HealthLiveValidateBeforeCall(progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for getV2HealthReady
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public okhttp3.Call getV2HealthReadyCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/health/ready";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new okhttp3.Interceptor() {
                @Override
                public okhttp3.Response intercept(okhttp3.Interceptor.Chain chain) throws IOException {
                    okhttp3.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getV2HealthReadyValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {

        okhttp3.Call call = getV2HealthReadyCall(progressListener, progressRequestListener);
        return call;

    }

    /**
     * Server Ready
     * The \&quot;server ready\&quot; API indicates if the inference server is ready to handle inference requests. This can be used for Kubernetes readiness probes. 
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void getV2HealthReady() throws ApiException {
        getV2HealthReadyWithHttpInfo();
    }

    /**
     * Server Ready
     * The \&quot;server ready\&quot; API indicates if the inference server is ready to handle inference requests. This can be used for Kubernetes readiness probes. 
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> getV2HealthReadyWithHttpInfo() throws ApiException {
        okhttp3.Call call = getV2HealthReadyValidateBeforeCall(null, null);
        return apiClient.execute(call);
    }

    /**
     * Server Ready (asynchronously)
     * The \&quot;server ready\&quot; API indicates if the inference server is ready to handle inference requests. This can be used for Kubernetes readiness probes. 
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public okhttp3.Call getV2HealthReadyAsync(final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        okhttp3.Call call = getV2HealthReadyValidateBeforeCall(progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for postModelVersionInfer
     * @param body  (required)
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public okhttp3.Call postModelVersionInferCall(InferenceRequest body, String MODEL_NAME, String MODEL_VERSION, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/v2/models/{MODEL_NAME}/versions/{MODEL_VERSION}/infer"
            .replaceAll("\\{" + "MODEL_NAME" + "\\}", apiClient.escapeString(MODEL_NAME.toString()))
            .replaceAll("\\{" + "MODEL_VERSION" + "\\}", apiClient.escapeString(MODEL_VERSION.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new okhttp3.Interceptor() {
                @Override
                public okhttp3.Response intercept(okhttp3.Interceptor.Chain chain) throws IOException {
                    okhttp3.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postModelVersionInferValidateBeforeCall(InferenceRequest body, String MODEL_NAME, String MODEL_VERSION, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling postModelVersionInfer(Async)");
        }
        // verify the required parameter 'MODEL_NAME' is set
        if (MODEL_NAME == null) {
            throw new ApiException("Missing the required parameter 'MODEL_NAME' when calling postModelVersionInfer(Async)");
        }
        // verify the required parameter 'MODEL_VERSION' is set
        if (MODEL_VERSION == null) {
            throw new ApiException("Missing the required parameter 'MODEL_VERSION' when calling postModelVersionInfer(Async)");
        }

        okhttp3.Call call = postModelVersionInferCall(body, MODEL_NAME, MODEL_VERSION, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Inference
     * Performs inference using a specific version of a model. 
     * @param body  (required)
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @return InferenceResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public InferenceResponse postModelVersionInfer(InferenceRequest body, String MODEL_NAME, String MODEL_VERSION) throws ApiException {
        ApiResponse<InferenceResponse> resp = postModelVersionInferWithHttpInfo(body, MODEL_NAME, MODEL_VERSION);
        return resp.getData();
    }

    /**
     * Inference
     * Performs inference using a specific version of a model. 
     * @param body  (required)
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @return ApiResponse&lt;InferenceResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<InferenceResponse> postModelVersionInferWithHttpInfo(InferenceRequest body, String MODEL_NAME, String MODEL_VERSION) throws ApiException {
        okhttp3.Call call = postModelVersionInferValidateBeforeCall(body, MODEL_NAME, MODEL_VERSION, null, null);
        Type localVarReturnType = new TypeToken<InferenceResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Inference (asynchronously)
     * Performs inference using a specific version of a model. 
     * @param body  (required)
     * @param MODEL_NAME Name of the model (required)
     * @param MODEL_VERSION Version of the model (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public okhttp3.Call postModelVersionInferAsync(InferenceRequest body, String MODEL_NAME, String MODEL_VERSION, final ApiCallback<InferenceResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        okhttp3.Call call = postModelVersionInferValidateBeforeCall(body, MODEL_NAME, MODEL_VERSION, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<InferenceResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
